export const FETCH_DATA_REQ="FETCH_DATA"
export const FETCH_DATA_SUCCESS="FETCH_DATA"
export const FETCH_DATA_FAILED="FETCH_DATA"

export const EDIT_DATA="EDIT_DATA"
export const CREATE_DATA="CREATE_DATA"
export const DELETE_DATA="DELETE_DATA"

